{{- if not .Values.staticFileBucketname }}
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  namespace: config-connector
  annotations:
    cnrm.cloud.google.com/force-destroy: "true"
  labels:
    label-one: {{ .Values.Valueone }}
  # StorageBucket names must be globally unique. Replace ${PROJECT_ID?} with your project ID.
  name: {{ .Values.GCPName }}-{{ .Values.Valueone }}-st
spec:
  lifecycleRule:
    - action:
        type: Delete
      condition:
        age: 360
  versioning:
    enabled: true
{{- end }}
